name: 'SARIF Annotator'
description: 'Annotates code with results from a SARIF file'
author: 'SirYwell'
inputs:
  token:
    description: 'The token to use for GitHub API interactions'
    required: false
    default: ${{ github.token }}
  source:
    description: 'The service that provides the SARIF file'
    required: false
  problems-path:
    description: 'The path to the SARIF file'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
