name: 'SARIF Annotator'
description: 'Annotates code with results from a SARIF file'
author: 'SirYwell'
inputs:
  token:
    description: 'The token to use for GitHub API interactions'
    required: false
    default: ${{ github.token }}
  source:
    description: 'The service that provides the SARIF file'
    required: false
  report-path:
    description: 'The path to the SARIF file'
    required: true
  baseline-state-filter:
    description: 'A comma-separated list of baseline states to include. If none is set, all results are included'
    default: ''
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: activity
  color: orange
